stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build /p:Configuration=Release

test:
  stage: test
  script:
    - dotnet test
  dependencies:
    - build