stages:
  - build
  - test
  - qualimetry

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build /p:Configuration=Release

test:
  stage: test
  script:
    - dotnet test
  dependencies:
    - build

qualimetry:
  stage: qualimetry
  script:
    - dotnet tool install --global dotnet-sonarscanner
    - dotnet sonarscanner begin /k:"be-on" /d:sonar.login="1b66983f7f6b483606accc1b8c02085fb20ed3cd" /d:sonar.host.url="https://sonarqube.sharprover.wilders.dev"
    - dotnet build
    - dotnet sonarscanner end /d:sonar.login="1b66983f7f6b483606accc1b8c02085fb20ed3cd"